name: Unit tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v1  # not v2!
      with:
        path: $Qt6_DIR
        key: ${{runner.os}}-QtCache

    - name: Install Qt
      uses: jurplel/install-qt-action@v2.14.0
      with:
        dir: ${{github.workspace}}
        cached: ${{steps.cache-qt.outputs.cache-hit}}
        version: 6.0.4

    - name: Installing dependancies packages
      run: sudo apt-get install -y lcov libcurl4-gnutls-dev libasound2-dev
    
    - name: Starting setup.sh script
      working-directory: ${{github.workspace}}
      run: ./setup.sh

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_PREFIX_PATH=$Qt6_DIR

    - name: Build
      run: cmake --build ${{github.workspace}}/build

    - name: Run tests
      working-directory: ${{github.workspace}}/build
      run: ./Tests/4tracks_tests

    - name: Generate code coverage report
      working-directory: ${{github.workspace}}/build
      run: lcov --no-external --directory Source/CMakeFiles/4tracks_lib.dir/ --base-directory ../Source --capture --output coverage-summary.info
      
    - uses: codecov/codecov-action@v2
      with:
        files: ${{github.workspace}}/build/coverage-summary.info
